### ISSUE TITLE
Error,is dataset?

### ISSUE THREAD

**Issue by makeyyp** [bnm6900030/swintormer#4]
![d3ff89b273002dc783e9fb236848250](https://github.com/bnm6900030/swintormer/assets/137139484/010fb5e0-5fbe-4cd3-bba4-dc91fc6ed347)
![image](https://github.com/bnm6900030/swintormer/assets/137139484/10cfc023-e358-4e81-8936-0940f78435ce)

**Comment by bnm6900030** [comment]
The basicsr package does not need to be installed, it can be run directly with my open source code.
Because the official basicsr package does not define classes to load dual-pixel datasets.
